/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.chetan.androidavrodemo.model;  
@SuppressWarnings("all")
/** A Person is someone who can login to the system.

The first version of a Person record has been renamed from `Person` to `PersonV1` to prevent clashes between this and the newer version of the Person record.  The Java code can continue to use the `Person` class and will gain from the new fields when the new version is generated. */
@org.apache.avro.specific.AvroGenerated
public class PersonV1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PersonV1\",\"namespace\":\"com.chetan.androidavrodemo.model\",\"doc\":\"A Person is someone who can login to the system.\\n\\nThe first version of a Person record has been renamed from `Person` to `PersonV1` to prevent clashes between this and the newer version of the Person record.  The Java code can continue to use the `Person` class and will gain from the new fields when the new version is generated.\",\"fields\":[{\"name\":\"username\",\"type\":\"string\",\"doc\":\"The username that uniquely identifies the user\"},{\"name\":\"password\",\"type\":\"string\",\"doc\":\"A password, hopefully encrypted\"},{\"name\":\"joined_on\",\"type\":\"long\",\"doc\":\"The offset from the UTC epoch when the user joined in on the fun\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** The username that uniquely identifies the user */
  @Deprecated public CharSequence username;
  /** A password, hopefully encrypted */
  @Deprecated public CharSequence password;
  /** The offset from the UTC epoch when the user joined in on the fun */
  @Deprecated public long joined_on;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public PersonV1() {}

  /**
   * All-args constructor.
   */
  public PersonV1(CharSequence username, CharSequence password, Long joined_on) {
    this.username = username;
    this.password = password;
    this.joined_on = joined_on;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public Object get(int field$) {
    switch (field$) {
    case 0: return username;
    case 1: return password;
    case 2: return joined_on;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: username = (CharSequence)value$; break;
    case 1: password = (CharSequence)value$; break;
    case 2: joined_on = (Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'username' field.
   * The username that uniquely identifies the user   */
  public CharSequence getUsername() {
    return username;
  }

  /**
   * Sets the value of the 'username' field.
   * The username that uniquely identifies the user   * @param value the value to set.
   */
  public void setUsername(CharSequence value) {
    this.username = value;
  }

  /**
   * Gets the value of the 'password' field.
   * A password, hopefully encrypted   */
  public CharSequence getPassword() {
    return password;
  }

  /**
   * Sets the value of the 'password' field.
   * A password, hopefully encrypted   * @param value the value to set.
   */
  public void setPassword(CharSequence value) {
    this.password = value;
  }

  /**
   * Gets the value of the 'joined_on' field.
   * The offset from the UTC epoch when the user joined in on the fun   */
  public Long getJoinedOn() {
    return joined_on;
  }

  /**
   * Sets the value of the 'joined_on' field.
   * The offset from the UTC epoch when the user joined in on the fun   * @param value the value to set.
   */
  public void setJoinedOn(Long value) {
    this.joined_on = value;
  }

  /** Creates a new PersonV1 RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }
  
  /** Creates a new PersonV1 RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }
  
  /** Creates a new PersonV1 RecordBuilder by copying an existing PersonV1 instance */
  public static Builder newBuilder(PersonV1 other) {
    return new Builder(other);
  }
  
  /**
   * RecordBuilder for PersonV1 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PersonV1>
    implements org.apache.avro.data.RecordBuilder<PersonV1> {

    private CharSequence username;
    private CharSequence password;
    private long joined_on;

    /** Creates a new Builder */
    private Builder() {
      super(PersonV1.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.username)) {
        this.username = data().deepCopy(fields()[0].schema(), other.username);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.password)) {
        this.password = data().deepCopy(fields()[1].schema(), other.password);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.joined_on)) {
        this.joined_on = data().deepCopy(fields()[2].schema(), other.joined_on);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing PersonV1 instance */
    private Builder(PersonV1 other) {
            super(PersonV1.SCHEMA$);
      if (isValidValue(fields()[0], other.username)) {
        this.username = data().deepCopy(fields()[0].schema(), other.username);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.password)) {
        this.password = data().deepCopy(fields()[1].schema(), other.password);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.joined_on)) {
        this.joined_on = data().deepCopy(fields()[2].schema(), other.joined_on);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'username' field */
    public CharSequence getUsername() {
      return username;
    }
    
    /** Sets the value of the 'username' field */
    public Builder setUsername(CharSequence value) {
      validate(fields()[0], value);
      this.username = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'username' field has been set */
    public boolean hasUsername() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'username' field */
    public Builder clearUsername() {
      username = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'password' field */
    public CharSequence getPassword() {
      return password;
    }
    
    /** Sets the value of the 'password' field */
    public Builder setPassword(CharSequence value) {
      validate(fields()[1], value);
      this.password = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'password' field has been set */
    public boolean hasPassword() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'password' field */
    public Builder clearPassword() {
      password = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'joined_on' field */
    public Long getJoinedOn() {
      return joined_on;
    }
    
    /** Sets the value of the 'joined_on' field */
    public Builder setJoinedOn(long value) {
      validate(fields()[2], value);
      this.joined_on = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'joined_on' field has been set */
    public boolean hasJoinedOn() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'joined_on' field */
    public Builder clearJoinedOn() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public PersonV1 build() {
      try {
        PersonV1 record = new PersonV1();
        record.username = fieldSetFlags()[0] ? this.username : (CharSequence) defaultValue(fields()[0]);
        record.password = fieldSetFlags()[1] ? this.password : (CharSequence) defaultValue(fields()[1]);
        record.joined_on = fieldSetFlags()[2] ? this.joined_on : (Long) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
